import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { resolveDbConfig, type DbConfig } from '../core/config.js';

/**
 * `drizzle-kit migrate` (unlike `generate`) only accepts a --config file, no direct
 * --schema/--out/--url flags — so we write one, derived from ratchet.config.ts, into the
 * same gitignored generatedDir as schema.ts/validators.ts/registry.ts (§6: a build artifact,
 * not something hand-edited).
 *
 * `schema`/`out` are written relative to `cwd`, not as absolute paths — matching every
 * drizzle-kit example in its own docs. Absolute paths here hit an internal drizzle-kit path-join
 * quirk (its own journal/snapshot validation concatenates a base path with `schema`/`out` rather
 * than resolving them, producing a mangled path like `.//Users/...` and an ENOENT) — relative
 * paths, resolved the conventional way, don't trigger it.
 *
 * `driver: 'sqlite'` maps to drizzle-kit's `'turso'` dialect, not `'sqlite'` — `'turso'`'s
 * `dbCredentials` shape (`{ url, authToken? }`) is exactly what `@libsql/client` itself takes and
 * works transparently with a local `file:` URL today and a remote Turso URL later; plain
 * `'sqlite'` targets a different, non-libsql local-only driver with no `authToken` credential at
 * all (see `docs/adr/0004-sqlite-libsql-second-db-driver.md`).
 */
export async function writeDrizzleKitConfig(cwd: string, generatedDir: string, migrationsDir: string, dbConfig: DbConfig): Promise<string> {
  await mkdir(generatedDir, { recursive: true });
  const schemaFile = path.join(generatedDir, 'schema.ts');
  const configFile = path.join(generatedDir, 'drizzle.config.ts');

  const relativeSchema = path.relative(cwd, schemaFile);
  const relativeOut = path.relative(cwd, migrationsDir);

  const resolved = resolveDbConfig(dbConfig);
  const dialectLine = resolved.driver === 'sqlite' ? `  dialect: 'turso',` : `  dialect: 'postgresql',`;
  const credentialsLine =
    resolved.driver === 'sqlite'
      ? `  dbCredentials: { url: ${JSON.stringify(resolved.url)}${resolved.authToken !== undefined ? `, authToken: ${JSON.stringify(resolved.authToken)}` : ''} },`
      : `  dbCredentials: { url: ${JSON.stringify(resolved.connectionString)} },`;

  const src = [
    `// GENERATED by \`ratchet migrate\` — do not edit.`,
    `import { defineConfig } from 'drizzle-kit';`,
    ``,
    `export default defineConfig({`,
    dialectLine,
    `  schema: ${JSON.stringify(relativeSchema)},`,
    `  out: ${JSON.stringify(relativeOut)},`,
    credentialsLine,
    `});`,
    ``,
  ].join('\n');

  await writeFile(configFile, src, 'utf8');
  return configFile;
}
