import type { Dialect } from '../core/db.js';
import type { FieldDefinition } from '../core/field.js';
import type { ModelDefinition } from '../core/model.js';
import { buildJunctionModel, junctionColumnsOf, manyToManyFieldsOf, type ManyToManyRelation } from '../core/many-to-many.js';
import { injectInverseReferenceFields } from '../core/reference-to-many.js';
import { toSnakeCase } from '../core/naming.js';
import type { ScannedModel } from './scan.js';

const HEADER = `// GENERATED by \`ratchet generate\` — do not edit.\n// Source: models/**/*.model.ts\n\n`;

function tableVar(modelName: string): string {
  return `${modelName}Table`;
}

/** `sqlite-core` has no `varchar`/`uuid`/`jsonb`/`timestamp` builders and no fixed-precision
 * `numeric` — see the per-kind comments below for the SQLite equivalent chosen and why (mirrors
 * the rationale recorded in `docs/adr/0004-sqlite-libsql-second-db-driver.md`). */
function columnExpr(key: string, f: FieldDefinition, dialect: Dialect): string {
  const col = toSnakeCase(key);
  let expr: string;
  switch (f.kind) {
    case 'string':
      // sqlite-core has no varchar builder (no length-enforced string type) — `maxLength` becomes
      // advisory (Zod-validation-only) under sqlite, same as it already is for anything beyond
      // what the DB enforces on Postgres.
      expr =
        dialect === 'postgres'
          ? f.maxLength !== undefined
            ? `varchar('${col}', { length: ${f.maxLength} })`
            : `varchar('${col}')`
          : `text('${col}')`;
      break;
    case 'text':
      expr = `text('${col}')`;
      break;
    case 'integer':
      expr = `integer('${col}')`;
      break;
    case 'decimal':
      // sqlite-core's `numeric()` takes no precision/scale (NUMERIC affinity only, no fixed
      // precision at the storage level) — same "advisory beyond the DB" tradeoff as `string` above.
      expr = dialect === 'postgres' ? `numeric('${col}', { precision: ${f.precision}, scale: ${f.scale} })` : `numeric('${col}')`;
      break;
    case 'boolean':
      // sqlite-core has no native boolean builder — `integer(mode: 'boolean')` is its documented
      // idiom, storing 0/1 and round-tripping as a JS boolean transparently.
      expr = dialect === 'postgres' ? `boolean('${col}')` : `integer('${col}', { mode: 'boolean' })`;
      break;
    case 'datetime':
      // Postgres: Q25, timestamptz not bare timestamp — avoids the classic session-timezone
      // footgun by always storing/reading an absolute UTC instant. SQLite has no timezone-aware
      // column type at all; `text(mode: 'string')` storing the same ISO-8601 UTC string
      // `toDriverValue` (core/persistence.ts) already writes for Postgres is the SQLite
      // equivalent — an absolute instant either way, and it keeps `core/serialize.ts`'s raw-query
      // timestamp handling convergent across dialects rather than needing a second text format.
      expr = dialect === 'postgres' ? `timestamp('${col}', { withTimezone: true })` : `text('${col}', { mode: 'string' })`;
      break;
    case 'enum':
      // §4: varchar/text + CHECK, not a native enum type — see the check() constraint emitted
      // below (extraConfigLines). sqlite-core's check() API is the same shape as pg-core's.
      expr = dialect === 'postgres' ? `varchar('${col}')` : `text('${col}')`;
      break;
    case 'json':
    case 'file':
      // sqlite-core's documented JSON idiom: `text(mode: 'json')` round-trips a JS value through
      // `JSON.stringify`/`parse` transparently, matching jsonb's ergonomics from the caller's side.
      expr = dialect === 'postgres' ? `jsonb('${col}')` : `text('${col}', { mode: 'json' })`;
      break;
    case 'reference':
      // Q6: RESTRICT — refuse a hard-delete that would orphan referencing rows. sqlite-core has no
      // `uuid` builder; not an issue since ids are always app-generated `uuidv7()` strings, never
      // DB-generated (core/id.ts) — a `text` column round-trips them identically on both dialects.
      expr =
        dialect === 'postgres'
          ? `uuid('${col}').references(() => ${tableVar(f.targetModel)}.id, { onDelete: 'restrict' })`
          : `text('${col}').references(() => ${tableVar(f.targetModel)}.id, { onDelete: 'restrict' })`;
      break;
    case 'tree':
      // Self-referencing FK — `f.targetModel` is always this same model (see `TreeFieldDefinition`
      // in core/field.ts), so `tableVar(f.targetModel)` here resolves to the very table constant
      // being defined; Drizzle supports this as long as the reference stays a lazy `() => ...`
      // callback, same as any other `reference` column. RESTRICT for the same reason as `reference`
      // above (Q6) — it only guards a real hard-delete, same caveat as `reference`, since the
      // generic router's normal DELETE is a soft delete that never touches this FK either way.
      expr =
        dialect === 'postgres'
          ? `uuid('${col}').references(() => ${tableVar(f.targetModel)}.id, { onDelete: 'restrict' })`
          : `text('${col}').references(() => ${tableVar(f.targetModel)}.id, { onDelete: 'restrict' })`;
      break;
    case 'modelRef':
    case 'actionRef':
    case 'fieldRef':
      // like 'enum': no length cap — real value enforcement is a per-request registry check,
      // not something the schema can express (see core/validation.ts).
      expr = dialect === 'postgres' ? `varchar('${col}')` : `text('${col}')`;
      break;
    case 'manyToMany':
      // never reaches here — `emitTable` filters manyToMany fields out of `model.fields` before
      // calling `columnExpr` (there's no column to emit; the relation is backed by a separate
      // junction table, see `emitJunctionTable` below). Kept as an explicit throw, not folded into
      // a `default:`, so adding a future field kind without a case here is a compile error.
      throw new Error(`columnExpr: '${col}' is a manyToMany field — it has no column, see emitTable`);
    case 'referenceToMany':
      // never reaches here — `emitTable` filters referenceToMany fields out of `model.fields` before
      // calling `columnExpr`: the FK column lives on the *target* model (injected by
      // `injectInverseReferenceFields`), not on this declaring model. Explicit throw, not a `default:`.
      throw new Error(`columnExpr: '${col}' is a referenceToMany field — its FK column lives on the target model`);
  }
  if (f.required || f.default !== undefined) expr += '.notNull()';
  if (f.default !== undefined) expr += `.default(${JSON.stringify(f.default)})`;
  return expr;
}

function extraConfigLines(model: ModelDefinition): string[] {
  const lines: string[] = [];
  for (const [key, f] of Object.entries(model.fields)) {
    const col = toSnakeCase(key);
    if (f.indexed) {
      lines.push(`  index('${model.name}_${col}_idx').on(table.${key}),`);
    }
    if (f.unique) {
      // §4: partial unique index, not a plain UNIQUE — a soft-deleted row must not permanently
      // block reuse of its unique value. sqlite-core's uniqueIndex().where() supports the same
      // partial-index syntax (SQLite has native partial index support), so this needs no dialect
      // branch.
      lines.push(
        `  uniqueIndex('${model.name}_${col}_unique_idx').on(table.${key}).where(sql` +
          '`' +
          '${table.deletedAt} IS NULL' +
          '`' +
          `),`,
      );
    }
    if (f.kind === 'enum') {
      const values = f.values.map((v) => `'${v.replace(/'/g, "''")}'`).join(', ');
      lines.push(
        `  check('${model.name}_${col}_check', sql` +
          '`' +
          '${table.' +
          key +
          '} IN (' +
          values +
          ')' +
          '`' +
          `),`,
      );
    }
  }
  return lines;
}

function emitTable(model: ModelDefinition, dialect: Dialect, extraLines: string[] = []): string {
  const varName = tableVar(model.name);
  const idCol = dialect === 'postgres' ? `uuid('id').primaryKey()` : `text('id').primaryKey()`;
  const tsCol = (name: string) =>
    dialect === 'postgres' ? `timestamp('${name}', { withTimezone: true })` : `text('${name}', { mode: 'string' })`;
  const createdByCol =
    dialect === 'postgres'
      ? `uuid('created_by_id').references(() => ${tableVar('users')}.id, { onDelete: 'restrict' })`
      : `text('created_by_id').references(() => ${tableVar('users')}.id, { onDelete: 'restrict' })`;
  const columnLines = [
    `  id: ${idCol},`,
    `  createdAt: ${tsCol('created_at')}.notNull(),`,
    `  updatedAt: ${tsCol('updated_at')}.notNull(),`,
    `  deletedAt: ${tsCol('deleted_at')},`,
    // Q30: audit trail, not ownership — nullable (self-registration and other unauthenticated
    // creates have no actor to stamp) and RESTRICT like every other reference() column, but never
    // declarable via field.* and never touched by the ownership-scope helpers/updateRow.
    `  createdById: ${createdByCol},`,
    // manyToMany has no column of its own — it's backed by a separate junction table instead
    // (see emitJunctionTable), so it's excluded here rather than passed to columnExpr. referenceToMany
    // is excluded for the same reason: its FK column lives on the *target* model (injected by
    // `injectInverseReferenceFields` into `generateSchemaSource`'s augmented models), not here.
    ...Object.entries(model.fields)
      .filter(([, f]) => f.kind !== 'manyToMany' && f.kind !== 'referenceToMany')
      .map(([key, f]) => `  ${key}: ${columnExpr(key, f, dialect)},`),
  ];
  // Auto-indexed unconditionally: `id`, `createdAt`, `updatedAt`, `createdById` are treated as
  // implicitly sortable/filterable by the router (src/router/fields.ts) since a model author has
  // no way to declare `indexed: true` on a column they didn't author — "sort by most recent" and
  // "show me what I created" both need a real index to back them, not just a rule that allows the
  // query.
  const extra = [
    `  index('${model.name}_created_at_idx').on(table.createdAt),`,
    `  index('${model.name}_updated_at_idx').on(table.updatedAt),`,
    `  index('${model.name}_created_by_id_idx').on(table.createdById),`,
    ...extraConfigLines(model),
    ...extraLines,
  ];

  const tableFn = dialect === 'postgres' ? 'pgTable' : 'sqliteTable';
  let src = `export const ${varName} = ${tableFn}('${model.tableName}', {\n${columnLines.join('\n')}\n}`;
  if (extra.length > 0) {
    src += `, (table) => [\n${extra.join('\n')}\n]`;
  }
  src += `);\n`;
  return src;
}

/** Emits the junction table backing one manyToMany relation — a normal table (see
 * `buildJunctionModel`, core/many-to-many.ts) plus one thing `field.*`'s own `unique: true` can't
 * express: a *compound* partial-unique index over both FK columns together, so the same pair can't
 * be attached twice while still allowing a re-attach after a prior soft-remove (same "partial
 * index, not plain UNIQUE" reasoning as `extraConfigLines`' per-field unique case above). */
function emitJunctionTable(relation: ManyToManyRelation, dialect: Dialect): string {
  const junctionModel = buildJunctionModel(relation);
  const cols = junctionColumnsOf(relation);
  const compoundUniqueLine =
    `  uniqueIndex('${junctionModel.name}_unique_idx').on(table.${cols.sourceColumn}, table.${cols.targetColumn}).where(sql` +
    '`' +
    '${table.deletedAt} IS NULL' +
    '`' +
    `),`;
  return emitTable(junctionModel, dialect, [compoundUniqueLine]);
}

/** One shared, fixed-shape table backing every Domain's Domain Settings (ADR 0002) — a single
 * row per Domain, `values` a jsonb blob validated at the application layer against that Domain's
 * declared `field.*` schema (`core/validation.ts`'s `buildDomainSettingsSchema`), never against
 * per-domain Postgres columns. Emitted unconditionally, the same way the built-in auth tables
 * always exist regardless of whether a consuming app declares any Domain Settings of its own —
 * this keeps the table's own shape stable across `ratchet generate` runs even as domains are
 * added, renamed, or have fields added to their settings. */
function emitDomainSettingsTable(dialect: Dialect): string {
  const tableFn = dialect === 'postgres' ? 'pgTable' : 'sqliteTable';
  const domainCol = dialect === 'postgres' ? `varchar('domain').primaryKey()` : `text('domain').primaryKey()`;
  const valuesCol = dialect === 'postgres' ? `jsonb('values').notNull().default({})` : `text('values', { mode: 'json' }).notNull().default({})`;
  const updatedAtCol =
    dialect === 'postgres' ? `timestamp('updated_at', { withTimezone: true }).notNull()` : `text('updated_at', { mode: 'string' }).notNull()`;
  return [
    `export const ratchetDomainSettingsTable = ${tableFn}('ratchet_domain_settings', {`,
    `  domain: ${domainCol},`,
    `  values: ${valuesCol},`,
    `  updatedAt: ${updatedAtCol},`,
    `});\n`,
  ].join('\n');
}

export function generateSchemaSource(scanned: ScannedModel[], dialect: Dialect): string {
  const imports =
    dialect === 'postgres'
      ? [
          `import {`,
          `  pgTable,`,
          `  varchar,`,
          `  text,`,
          `  integer,`,
          `  numeric,`,
          `  boolean,`,
          `  timestamp,`,
          `  jsonb,`,
          `  uuid,`,
          `  index,`,
          `  uniqueIndex,`,
          `  check,`,
          `} from 'drizzle-orm/pg-core';`,
          `import { sql } from 'drizzle-orm';`,
          ``,
        ].join('\n')
      : [
          `import {`,
          `  sqliteTable,`,
          `  text,`,
          `  integer,`,
          `  numeric,`,
          `  index,`,
          `  uniqueIndex,`,
          `  check,`,
          `} from 'drizzle-orm/sqlite-core';`,
          `import { sql } from 'drizzle-orm';`,
          ``,
        ].join('\n');

  // Augment every model with the inverse `reference` field each `referenceToMany` declaration
  // implies on its target (e.g. `Article.comments -> Comment.articleId`), so `emitTable` emits the
  // FK column + index on the target table. The originals are untouched; these clones are codegen-only.
  const augmentedModels = injectInverseReferenceFields(scanned.map((s) => s.model));

  const tables = augmentedModels.map((model) => emitTable(model, dialect)).join('\n');

  // Every manyToMany field declared across every scanned model gets its own junction table — only
  // the declaring (source) side is scanned here, since the field key already namespaces the table
  // name (`core/many-to-many.ts`'s `junctionColumns`), so there's exactly one declaration per
  // relation to emit from, even though the relation is queryable from both sides at request time.
  const junctionTables = scanned
    .flatMap(({ model }) => manyToManyFieldsOf(model))
    .map((relation) => emitJunctionTable(relation, dialect))
    .join('\n');

  return HEADER + imports + '\n' + tables + '\n' + junctionTables + '\n' + emitDomainSettingsTable(dialect);
}
