import { mkdir, writeFile, readFile, readdir, access } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// The scaffold lives as a real, readable project tree next to the CLI (`src/cli/stubs/`) — edit
// those files directly, they are copied verbatim into the new project. `src/cli/commands/` and the
// published `dist/cli/commands/` are both one level below their `cli/stubs/`, so this resolves in
// both; `scripts/build.ts` copies the tree into `dist/cli/stubs/`.
const STUBS_DIR = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'stubs');

// Stub files that land under a different name in the target project. `.gitignore` can't be shipped
// verbatim — npm strips/renames any `.gitignore` inside a package tarball — so it lives as
// `stubs/gitignore`. Keyed by the stub's path relative to STUBS_DIR (POSIX separators).
const RENAME_ON_WRITE: Record<string, string> = {
  gitignore: '.gitignore',
};

// Empty directories the workflow expects to exist but that carry no stub file (git/npm don't track
// empty dirs). `.ratchet/` is regenerated by `ratchet generate`; `drizzle/migrations/` is where
// `drizzle-kit generate` writes SQL.
const EMPTY_DIRS = ['.ratchet', path.join('drizzle', 'migrations')];

function sanitizePackageName(dirName: string): string {
  const cleaned = dirName
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/^-+|-+$/g, '');
  return cleaned.length > 0 ? cleaned : 'ratchet-app';
}

async function exists(p: string): Promise<boolean> {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

/** All files under `dir`, as paths relative to it with POSIX separators. */
async function collectFiles(dir: string, base: string = dir): Promise<string[]> {
  const out: string[] = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...(await collectFiles(full, base)));
    } else {
      out.push(path.relative(base, full).split(path.sep).join('/'));
    }
  }
  return out;
}

async function writeIfAbsent(filePath: string, content: string, label: string): Promise<void> {
  if (await exists(filePath)) {
    console.log(`skipped ${label} (already exists)`);
    return;
  }
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, content, 'utf8');
  console.log(`wrote ${label}`);
}

/** `.gitignore` gets merge semantics, not overwrite-skip: create it, or append the ratchet block
 * if an existing file doesn't already cover `.ratchet`. */
async function mergeGitignore(cwd: string, stubContent: string): Promise<void> {
  const gitignorePath = path.join(cwd, '.gitignore');
  if (!(await exists(gitignorePath))) {
    await writeFile(gitignorePath, stubContent, 'utf8');
    console.log('wrote .gitignore');
    return;
  }
  const existing = await readFile(gitignorePath, 'utf8');
  if (!existing.includes('.ratchet')) {
    await writeFile(gitignorePath, `${existing}\n# ratchet\n${stubContent}`, 'utf8');
    console.log('updated .gitignore');
  } else {
    console.log('skipped .gitignore (already covers .ratchet)');
  }
}

/** Scaffolds a full starter project from the `stubs/` tree — package.json, tsconfig.json,
 * ratchet.config.ts, an example model, drizzle/migrations/, and a working public site: a
 * hand-authored landing page, a `models/website/` content set (a `Page` model + a `Contact` model +
 * the `website` Domain Settings, all editable source), and the routes that render them plus the
 * contact form. No server entry file to write: `ratchet serve` (framework-owned, see
 * src/cli/commands/serve.ts) boots the API directly from ratchet.config.ts + the generated
 * registry. Never overwrites a file that's already there — safe to re-run in a partially set-up
 * directory. */
export async function runInit(cwd: string): Promise<void> {
  const pkgName = sanitizePackageName(path.basename(cwd));
  const rels = (await collectFiles(STUBS_DIR)).sort();

  for (const rel of rels) {
    const source = await readFile(path.join(STUBS_DIR, rel), 'utf8');
    const targetRel = RENAME_ON_WRITE[rel] ?? rel;

    if (targetRel === '.gitignore') {
      await mergeGitignore(cwd, source);
      continue;
    }

    // package.json is the only templated stub: its `name` follows the target directory.
    const content = rel === 'package.json' ? source.replace(/"name":\s*"ratchet-app"/, `"name": "${pkgName}"`) : source;

    await writeIfAbsent(path.join(cwd, targetRel), content, targetRel);
  }

  for (const dir of EMPTY_DIRS) {
    await mkdir(path.join(cwd, dir), { recursive: true });
  }

  console.log('');
  console.log('next steps:');
  console.log('  1. bun install');
  console.log('  2. bun run generate   (writes .ratchet/* + SQL migration files — no DATABASE_URL needed, uses ./local.db by default)');
  console.log('  3. bun run migrate && bun run serve   (or `bun run dev` for local push-based iteration)');
  console.log('  4. open the console, complete setup, then add your pages under Pages');
  console.log('');
  console.log('using Postgres or Turso instead of the local SQLite file? set DATABASE_URL (and driver: \'postgres\' in ratchet.config.ts for Postgres) before step 2.');
}
